name: build-docker-image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '7 0 * * sun'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout docker-software-base
      uses: actions/checkout@v2

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opensciencegrid/software-base
        tags: fresh,${{ steps.mkdatetag.outputs.dtag }}

  dispatch:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        dispatch-repo: [docker-frontier-squid, docker-xcache]
    steps:

    - name: dispatch build ${{ matrix.dispatch-repo }}
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: opensciencegrid/${{ matrix.dispatch-repo }}
        event-type: dispatch-build
